version: '3.1'

services:
  db:
    domainname: db
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_DB: bingo
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pwd
    ports:
      - 15432:5432

  flyway:
    domainname: flyway
    image: flyway/flyway
    command: -url=jdbc:postgresql://db:5432/bingo -schemas=bingo -user=root -password=pwd -connectRetries=60 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - db
