on:
  push:
    branches:
      - main
      - dev

jobs:
  front:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: actions/checkout@v4
      - run: yarn install
        working-directory: stream-bingo-frontend
      - run: yarn build
        working-directory: stream-bingo-frontend
  back:
    runs-on: ubuntu-latest  
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: actions/checkout@v4
      - run: yarn install
        working-directory: stream-bingo-backend
      - run: yarn build
        working-directory: stream-bingo-backend
  
