name: Deploy to dev

on: workflow_dispatch

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    name: Build frontend
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: actions/checkout@v4
      - run: yarn install
        name: install frontend
        working-directory: stream-bingo-frontend
      - run: yarn build
        name: build frontend
        working-directory: stream-bingo-frontend
      - uses: actions/upload-artifact@v4
        with:
          name: frontend
          path: ./stream-bingo-frontend/dist/stream-bingo-frontend/browser/

  build-backend:
    runs-on: ubuntu-latest
    name: Build backend
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: actions/checkout@v4
      - run: yarn install
        name: install backend
        working-directory: stream-bingo-backend
      - run: yarn build
        name: build backend
        working-directory: stream-bingo-backend
      - name: Add package.json to output
        run: cp package.json ./dist
        working-directory: stream-bingo-backend
      - uses: actions/upload-artifact@v4
        with:
          name: backend
          path: ./stream-bingo-backend/dist/
  deploy-to-dev:
    runs-on: ubuntu-latest
    name: Deploy to dev
    needs: [build-frontend, build-backend]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: frontend
          path: frontend/
      - uses: actions/download-artifact@v4
        with:
          name: backend
          path: backend/
      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
      - name: Adding Known Hosts
        run: ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
        env:
          SSH_HOST: ${{ secrets.VPS_IP }}
      - name: Deploy Backend and frontend
        env:
          SSH_KEY: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.VPS_IP }}
          SSH_USER: ${{ secrets.VPS_USER }}
        run: |
          rsync -avz ./frontend/ $SSH_USER@$SSH_HOST:/apps/stream-bingo-dev/frontend
          rsync -avz ./backend/ $SSH_USER@$SSH_HOST:/apps/stream-bingo-dev/backend
      - name: Install deps
        run: ssh $SSH_USER@$SSH_HOST 'yarn install --production=true --cwd /apps/stream-bingo-dev/backend'
        env:
          SSH_HOST: ${{ secrets.VPS_IP }}
          SSH_USER: ${{ secrets.VPS_USER }}
      - name: Setup config
        run: ssh $SSH_USER@$SSH_HOST 'cp /apps/stream-bingo-dev/config.yaml /apps/stream-bingo-dev/backend/config'
        env:
          SSH_HOST: ${{ secrets.VPS_IP }}
          SSH_USER: ${{ secrets.VPS_USER }}

